### ISSUE TITLE
Nagios >=4.4.3

### ISSUE THREAD

**Issue by scuq** [alerta/nagios-alerta#38]
**Issue Summary**
My nagios process is crashing if I enable the event broker,
can you verify if nagios >= 4.4.3 should work?

**Environment**
- OS: Linux
- API version: Newest
- Deployment: Docker

- Database: Postgres

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

Specifically, please provide all configuration files and debug log file output showing any errors.

**Comment by satterly** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
